[package]
name = "export-data"
version = "0.1.0"
edition = "2021"

[dependencies]
abc-uiautomation = { version = "1.0.0", path = "../abc-uiautomation" }
clap = { version = "4.5.23", features = ["derive"] }
help = "0.0.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
